version: "3.8"

services: 
  mongo:
      image: mongo
      container_name: mongo
      restart: always
      env_file: .env
      ports: 
        - ${DB_PORT}:27017
      environment:
        MONGO_INITDB_DATABASE: ${DB_NAME}
        MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  
  node:
      image: node:alpine
      container_name: node
      restart: always
      depends_on:
        - mongo
      links: 
        - mongo:${DB_LINK_NAME}
      env_file: .env
      ports: 
        - ${API_PORT}:${API_PORT}
      volumes:
        - .:/usr/src/app
      working_dir: /usr/src/app
      command: npm run dev